platformName: Android
platformVersion: 5.1.1
appPackage: com.jiandan.mobilelesson
appActivity: com.jiandan.mobilelesson.InstallOpenActivity
#appPackage: com.guideclasspad
#appActivity: com.guideclasspad.MainActivity
unicodeKeyboard: true
resetKeyboard: true
noReset: true
deviceName: 127.0.0.1:62025
host: "127.0.0.1"
port: "4725"