### 华为真机
#platformVersion: 8.1.0
#udid: FAJBB19521205897
#deviceName: Honor 8c
platformName: Android
platformVersion: 8.1.0
appPackage: com.jiandan.mobilelesson
appActivity: com.jiandan.mobilelesson.InstallOpenActivity
unicodeKeyboard: true
resetKeyboard: true
noReset: true
deviceName: FAJBB19521205897
host: "127.0.0.1"
port: "4723"